export type MediaType = 'film' | 'serie';

export interface Media {
  id: string;
  title: string;
  type: MediaType;
  genre: string[];
  year: number;
  rating: number;
  duration?: number;
  seasons?: number;
  director: string;
  tags: string[];
  summary: string;
  image?: string;
}

export const DATA: Media[] = [
  {
    id: '1',
    title: 'Inception',
    type: 'film',
    genre: ['Science-Fiction', 'Thriller'],
    year: 2010,
    rating: 4.8,
    duration: 148,
    director: 'Christopher Nolan',
    tags: ['reve', 'espionnage', 'mind-bending'],
    summary: `Un voleur qui s'infiltre dans les reves de ses cibles se voit offrir une chance de retrouver sa vie passee en echange d'un acte impossible : l'inception.`,
    image: 'https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKafter3EhNh.jpg',
  },
  {
    id: '2',
    title: 'Breaking Bad',
    type: 'serie',
    genre: ['Drame', 'Thriller'],
    year: 2008,
    rating: 4.9,
    seasons: 5,
    director: 'Vince Gilligan',
    tags: ['drogue', 'crime', 'transformation'],
    summary: `Un professeur de chimie atteint d'un cancer terminal se lance dans la fabrication de methamfetamine avec un ancien eleve pour assurer l'avenir de sa famille.`,
  },
  {
    id: '3',
    title: 'Interstellar',
    type: 'film',
    genre: ['Science-Fiction', 'Aventure'],
    year: 2014,
    rating: 4.7,
    duration: 169,
    director: 'Christopher Nolan',
    tags: ['espace', 'temps', 'survie'],
    summary: `Une equipe d'explorateurs voyage a travers un trou de ver dans l'espace pour assurer la survie de l'humanite.`,
  },
  {
    id: '4',
    title: 'Stranger Things',
    type: 'serie',
    genre: ['Science-Fiction', 'Horreur'],
    year: 2016,
    rating: 4.6,
    seasons: 4,
    director: 'Les Duffer Brothers',
    tags: ['annees 80', 'surnaturel', 'enfants'],
    summary: `Dans une petite ville, la disparition d'un enfant revele des mysteres impliquant des experiences secretes et des forces surnaturelles.`,
  },
  {
    id: '5',
    title: 'The Dark Knight',
    type: 'film',
    genre: ['Action', 'Drame'],
    year: 2008,
    rating: 4.9,
    duration: 152,
    director: 'Christopher Nolan',
    tags: ['batman', 'joker', 'gotham'],
    summary: `Batman affronte le Joker, un criminel anarchiste qui seme le chaos a Gotham City et pousse le heros dans ses derniers retranchements.`,
  },
  {
    id: '6',
    title: 'La Casa de Papel',
    type: 'serie',
    genre: ['Thriller', 'Crime'],
    year: 2017,
    rating: 4.4,
    seasons: 5,
    director: 'Alex Pina',
    tags: ['braquage', 'espagne', 'resistance'],
    summary: `Un genie du crime recrute huit voleurs pour braquer la Monnaie royale d'Espagne, prenant en otage 67 personnes.`,
  },
  {
    id: '7',
    title: 'Parasite',
    type: 'film',
    genre: ['Drame', 'Thriller'],
    year: 2019,
    rating: 4.8,
    duration: 132,
    director: 'Bong Joon-ho',
    tags: ['classes sociales', 'coree', 'famille'],
    summary: `La famille Kim, sans le sou, s'infiltre peu a peu dans la vie d'une riche famille, jusqu'a ce qu'un evenement inattendu bouleverse tout.`,
  },
  {
    id: '8',
    title: 'Game of Thrones',
    type: 'serie',
    genre: ['Fantastique', 'Drame'],
    year: 2011,
    rating: 4.5,
    seasons: 8,
    director: 'David Benioff',
    tags: ['medieval', 'dragons', 'pouvoir'],
    summary: `Plusieurs familles nobles se disputent le Trone de Fer des Sept Couronnes, tandis qu'une ancienne menace ressurgit au-dela du Mur.`,
  },
  {
    id: '9',
    title: 'Dune',
    type: 'film',
    genre: ['Science-Fiction', 'Aventure'],
    year: 2021,
    rating: 4.5,
    duration: 155,
    director: 'Denis Villeneuve',
    tags: ['desert', 'epice', 'politique'],
    summary: `Paul Atreides, jeune homme brillant, doit voyager sur la planete la plus dangereuse de l'univers pour assurer l'avenir de sa famille.`,
  },
  {
    id: '10',
    title: 'Dark',
    type: 'serie',
    genre: ['Science-Fiction', 'Mystere'],
    year: 2017,
    rating: 4.7,
    seasons: 3,
    director: 'Baran bo Odar',
    tags: ['voyage temporel', 'allemagne', 'famille'],
    summary: `Quatre familles d'une petite ville allemande sont confrontees a des disparitions d'enfants qui relevent une conspiration temporelle complexe.`,
  },
  {
    id: '11',
    title: 'The Witcher',
    type: 'serie',
    genre: ['Fantastique', 'Action'],
    year: 2019,
    rating: 4.2,
    seasons: 3,
    director: 'Lauren Schmidt Hissrich',
    tags: ['magie', 'monstre', 'destin'],
    summary: `Geralt de Riv, un chasseur de monstres solitaire, cherche sa place dans un monde ou les humains sont souvent plus dangereux que les betes.`,
  },
  {
    id: '12',
    title: 'Oppenheimer',
    type: 'film',
    genre: ['Drame', 'Histoire'],
    year: 2023,
    rating: 4.6,
    duration: 180,
    director: 'Christopher Nolan',
    tags: ['bombe atomique', 'guerre', 'science'],
    summary: `L'histoire du physicien J. Robert Oppenheimer et de son role dans le developpement de la premiere bombe atomique pendant la Seconde Guerre mondiale.`,
  },
];